Remove per-distro install scripts and improve some terminology
Removed the per-distro install scripts in favor of using environment
variables to store the stow module list. This makes it easier to use the
same distro on different systems while having a unique set of modules on
each machine.

Renamed the zsh_(distro)_only modules to follow a new pattern:
zsh_dist_(distro). There is no technical reason behind this change, I
just prefer the different names.

The .zsh_platform file has also been renamed to .zsh_dist

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,8 +2,18 @@
 # I am using zsh instead of bash. I was having some troubles using bash with
 # arrays. Didn't want to investigate, so I just did zsh
 
+if [[ -z $DOTFILES ]]; then
+    echo "warning: dotfiles directory not specified, defaulting to ${HOME}/.dotfiles"
+    DOTFILES=$HOME/.dotfiles
+fi
+
+if [[ -z $DOTFILES_STOW_FOLDERS ]]; then
+    echo "fatal: no stow modules specified! At least one module is required."
+    exit 1
+fi
+
 pushd $DOTFILES
-for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
+for folder in $(echo $DOTFILES_STOW_FOLDERS | sed "s/,/ /g")
 do
     echo "stow $folder"
     stow --dotfiles -D $folder
